// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyPDFToClipboard(arg1:string,arg2:string):Promise<boolean>;

export function OpenFilePicker():Promise<Array<main.FileMeta>>;

export function ProcessPDFFromPath(arg1:string,arg2:string):Promise<boolean>;

export function SavePDFFile(arg1:string,arg2:string):Promise<boolean>;
