// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyPDFToClipboard(arg1, arg2) {
  return window['go']['main']['App']['CopyPDFToClipboard'](arg1, arg2);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function ProcessPDFFromPath(arg1, arg2) {
  return window['go']['main']['App']['ProcessPDFFromPath'](arg1, arg2);
}

export function SavePDFFile(arg1, arg2) {
  return window['go']['main']['App']['SavePDFFile'](arg1, arg2);
}
